name: Building, Testing, and Pushing Archivy Container Image On Push and PRs To Master Branch

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'archivy/**'
      - '.github/workflows/build-on-push-master.yml'

jobs:
  BuildPushUntested:
    name: Build and push image with 'untested' tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files from repository
        uses: actions/checkout@v2
        with:
          ref: docker

      - name: Setting variables
        if: success()
        run: |
          date -u +'%Y-%m-%dT%H:%M:%SZ' > TIMESTAMP
          echo "${GITHUB_SHA}" | cut -c1-8 > SHORT_SHA
          echo "source" > IMAGE_TAG
          echo "uzayg" > DOCKER_USERNAME
          echo "docker.io/uzayg/archivy" > DOCKER_IMAGE

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v1.0.2
        with:
          install: true
          version: latest

      - name: Docker login
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "$( cat DOCKER_USERNAME )" --password-stdin docker.io

      # Build and push images with the tags:
      #   untested-source
      #   untested-[hash]
      - name: Run buildx to push untested image
        if: success()
        run: |
          docker build \
            --output type=image,name="$( cat DOCKER_IMAGE )",push=true \
            --build-arg BUILD_DATE="$( cat TIMESTAMP )" --build-arg VCS_REF="$( cat SHORT_SHA )" \
            --tag "$( cat DOCKER_IMAGE ):untested-$( cat IMAGE_TAG )" \
            --tag "$( cat DOCKER_IMAGE ):untested-$( cat SHORT_SHA )" \
            --file ./Dockerfile.source .

  ContainerTestAndScan:
    name: Test image with 'untested' tag using Hadolint, container-structure-test, Trivy, and Anchore
    runs-on: ubuntu-latest
    needs: [BuildPushUntested]
    steps:
      - name: Checkout files from repository
        uses: actions/checkout@v2
        with:
          ref: docker

      - name: Setting variables
        if: success()
        run: |
          echo "source" > IMAGE_TAG
          echo "docker.io/uzayg/archivy" > DOCKER_IMAGE

      # Required by container-structure-test so it can access the image name as an env var.
      - name: Set image name as variable
        if: success()
        run: echo "DOCKER_IMAGE_TAG=$(cat DOCKER_IMAGE):untested-$(cat IMAGE_TAG)" >> $GITHUB_ENV

      - name: Lint Dockerfile with Hadolint
        if: success()
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: "Dockerfile.source"

      # This is required by container-structure-test. Without this step, it fails to pull the image on its own 
      - name: Run image
        if: success()
        run: docker run --rm uzayg/archivy:untested-"$( cat IMAGE_TAG )" sleep 0.1

      - name: Test image with container-structure-test
        uses: plexsystems/container-structure-test-action@v0.2.0
        with:
          image: $DOCKER_IMAGE_TAG
          config: "./container-structure-test-source.yaml"

      - name: Scan for OS vulnerabilities in image using Trivy
        uses: aquasecurity/trivy-action@0.0.8
        with:
          image-ref: "$DOCKER_IMAGE_TAG"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Scan image and code for vulnerabilties using Anchore
        uses: anchore/scan-action@v1.0.8
        with:
          image-reference: "$DOCKER_IMAGE_TAG"
          dockerfile-path: "./Dockerfile.source"
          fail-build: true
          include-app-packages: true

  dockerBuildPush:
    name: Build and push image with release version tag
    runs-on: ubuntu-latest
    needs: [ContainerTestAndScan]
    steps:
      - name: Checkout files from repository
        uses: actions/checkout@v2
        with:
          ref: docker

      - name: Setting variables
        if: success()
        run: |
          date -u +'%Y-%m-%dT%H:%M:%SZ' > TIMESTAMP
          echo "${GITHUB_SHA}" | cut -c1-8 > SHORT_SHA
          echo "source" > IMAGE_TAG
          echo "uzayg" > DOCKER_USERNAME
          echo "docker.io/uzayg/archivy" > DOCKER_IMAGE

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v1.0.2
        with:
          install: true
          version: latest

      - name: Docker login
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "$( cat DOCKER_USERNAME )" --password-stdin docker.io

      # Build and push images with the tags
      #   source
      #   hash   - Commit hash(first 8 characters)
      - name: Build and push with Docker Buildx
        if: success()
        run: |
          docker build \
            --output type=image,name="$(cat DOCKER_IMAGE)",push=true \
            --build-arg BUILD_DATE="$( cat TIMESTAMP )" --build-arg VCS_REF="$( cat SHORT_SHA )" \
            --tag "$( cat DOCKER_IMAGE ):$( cat IMAGE_TAG )" \
            --tag "$( cat DOCKER_IMAGE ):$( cat SHORT_SHA )" \
            --file ./Dockerfile.source .

  deleteUntestedImage:
    name: Delete images with the 'untested' tag
    runs-on: ubuntu-latest
    needs: [dockerBuildPush]
    steps:
      - name: Setting variables
        if: success()
        run: |
          echo ${GITHUB_SHA} | cut -c1-8 > SHORT_SHA
          echo "source" > IMAGE_TAG
          echo "uzayg" > DOCKER_USERNAME
          echo "docker.io/uzayg/archivy" > DOCKER_IMAGE

      - name: Delete 'untested' image
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          docker run --rm lumir/remove-dockerhub-tag --user "$( cat DOCKER_USERNAME )" --password "${DOCKER_PASSWORD}" \
          "$( cat DOCKER_IMAGE ):untested-$( cat IMAGE_TAG )" "$( cat DOCKER_IMAGE ):untested-$( cat SHORT_SHA )"
